export const REGISTRY_CORE_CLIENT = "core"
export const REGISTRY_USER_NAME = "username"
export const REGISTRY_TOKEN = "token"
export const REGISTRY_GAME = "game"
export const REGISTRY_CONN = "conn"
export const REGISTRY_ROOM = "room"

export const EVENT_CHAT = "event_chat"
export const EVENT_ROOM_DETAILS = "event_room_details"
export const EVENT_UNO_CUSTOM = "event_uno_custom"
export const EVENT_EXPLODING_CUSTOM = "event_exploding_kitten_custom"